version: '3'
services:
  jupyter-lab:
    image: jupyter/datascience-notebook:lab-3.6.3
    container_name: jupyter-lab
    ports:
      - 127.0.0.1:8888:8888
    volumes:
      - jupyter:/home/jovyan/
    networks:
      - jupyter
volumes:
  jupyter:
    name: jupyter-lab
networks:
  jupyter:
    name: jupyter-lab

